baseURL: https://OverlyDev.github.io/Homelab/
languageCode: en-us
title: OverlyDev Homelab
theme: hugo-PaperMod

# Check on this later
enableGitInfo: true

menus:
  main:
    - identifier: posts
      name: Posts
      pageRef: /posts/
      weight: 10
    - identifier: about
      name: About
      pageref: /about/
      weight: 100

params:
  # Always dark mode
  defaultTheme: dark
  disableThemeToggle: true

  # Reading time on pages
  #   disable on pages with params:showReadingTime: false
  showReadingTime: true
  
  # Clean up the home page
  profileMode:
    enabled: true
    title: Welcome
    subtitle: There's some stuff about things so feel free to poke around!
    imageUrl: https://github.com/OverlyDev.png

markup:
  goldmark:
    parser:
      wrapStandAloneImageWithinParagraph: false