# The baseURL is set during the deployment on GitHub/Cloudflare pages
#   and not actually necessary to set here, which makes local testing simpler
# baseURL: https://OverlyDev.github.io/Homelab/
languageCode: en-us
title: OverlyDev Homelab
theme: ["hugo-notice", "hugo-PaperMod"]

# Check on this later
enableGitInfo: true

menus:
  main:
    - identifier: posts
      name: Posts
      pageRef: /posts/
      weight: 10
    - identifier: ideas
      name: Ideas
      pageRef: /ideas-and-inspiration/
      weight: 20
    - identifier: about
      name: About
      pageRef: /about/
      weight: 100

params:
  # Always dark mode
  defaultTheme: dark
  disableThemeToggle: true

  # Reading time on pages
  #   disable on pages with params:showReadingTime: false
  showReadingTime: true

  # Clean up the home page
  profileMode:
    enabled: true
    title: Welcome
    subtitle: There's some stuff about things so feel free to poke around!
    imageUrl: https://github.com/OverlyDev.png

markup:
  goldmark:
    parser:
      # Sauce: https://gohugo.io/getting-started/configuration-markup/#parserwrapstandaloneimagewithinparagraph
      wrapStandAloneImageWithinParagraph: false
